# configs/client_vars.yaml
NAME: "name"
CLIENT_ID: "client_123"
CLIENT_SECRET: "supersecret"
BUCKET_NAME: "bronze"
TOKEN_URL: "https://wwww.token_url.com/auth"
API_URL: "api_url"
API_PATH: "api_path"
AUTH_TYPE: "oauth2"